### ISSUE TITLE
CodeIgniter 2.x compatibility

### ISSUE THREAD

**Issue by adam-becker** [peachpiecompiler/peachpie#879] opened 2020-11-04 21:56 UTC
I see under the projects for this repo that CodeIgniter is present, with the description stating:

> WIP: CodeIgniter running on .NET Core. Functional for older versions, but not for the most recent ones yet.

I'm not sure if 2.x is considered and `older version` but I was trying to get it to work and ran into one major, blocking issue. The library is using `eval()` to dynamically create a class in `./system/database/DB.php`:

```php
if ( ! isset($active_record) OR $active_record == TRUE)
{
    require_once(BASEPATH.'database/DB_active_rec.php');

    if ( ! class_exists('CI_DB'))
    {
        eval('class CI_DB extends CI_DB_active_record { }');
    }
}
else
{
    if ( ! class_exists('CI_DB'))
    {
        eval('class CI_DB extends CI_DB_driver { }');
    }
}
```

**Comment by adam-becker** [comment] 2020-11-04 22:18
For reference, I'm trying to use `rogeriopradoj/codeigniter@2.2.6` from packagist.

**Comment by adam-becker** [comment] 2020-11-05 02:49
I found a workaround for the class eval issue; define the class manually :man_shrugging:. Once I had that I ran into the next issue, which is that it seems the `eval()` statements in question don't actually emit the class.

I wouldn't expect this kind of thing to be high on the priority list, since it seems like a pretty narrow use case.

With those fixes in place, the application runs without issues.

**Comment by jakubmisek** [comment] 2020-11-06 09:36
Good to know, basically `eval()` is supported; however, if somewhere in the code is a class that extends `CI_DB`, the compiler won't get it.

Removing `eval()` is recommended.

Also, I don't understand the `eval()` here in the first place :)

**Comment by adam-becker** [comment] 2020-11-06 16:32
It's a little tricky here, since I'm grabbing `codeigniter` from composer, I can't statically make the `eval` change without something hacky like a `sed` before build :wink:

Is this something that will never be supported by PeachPie? Knowing the answer will determine if I go the `sed` route or not.

**Comment by bfistein** [comment] 2020-11-07 09:34
Little sidenote - have you tested more recent versions of CodeIgniter as well? No idea how much it changed between versions 2 and 4, but I'd imagine it should be pretty close to working, if not already functioning out of the box.

**Comment by jakubmisek** [comment] 2020-11-08 11:12
@adam-becker eval() is already supported by PeachPie, the only tricky thing is extending a dynamically compiled class - the compiler does not allow that in version 1.0. The following won't work in `1.0`:

```php
<?php
eval(' class X { } ');
// ...
class Y extends X { } // compiler error: PHP4044: Type name 'X' could not be resolved
```

In version `1.1` there is a plan to fully support those constructs; as a result, the compilation of class Y will be postponed to run time. The reason why we don't do it already is it's a bit tricky to keep track of all the dependencies between eval'ed code, losing performance because the compiler cannot refer to `Y` directly whenever it's used, and mostly it's a very special case not much needed by modern PHP frameworks.

---

Question: Do you have an idea why they use `eval()` in your example at https://github.com/peachpiecompiler/peachpie/issues/879#issue-736449482?

**Comment by adam-becker** [comment] 2020-11-13 19:06
> Question: Do you have an idea why they use `eval()` in your example at [#879 (comment)](https://github.com/peachpiecompiler/peachpie/issues/879#issue-736449482)?

@jakubmisek I think that's a question for the CodeIgniter team, they may have been under the assumption that they had to do it that way instead of just defining the class in the `if`/`else`?

@bfistein More recent version of CodeIgniter seem to have removed the eval, but I don't know if the newer versions are backwards compatible with the `2.x` line. Given that I'm working with a pretty large app built in CodeIgniter I'd have to do a lot of testing (No automated tests either) to make sure nothing breaks after upgrading.

**Comment by bfistein** [comment] 2020-11-13 20:35
Gotcha, I was just wondering if you had tested some sort of boiler plate in a more recent version.

**Comment by jackflyer** [comment] 2020-12-25 07:09
Also It will fail conditionally loading file using `file_exists` and `is_dir` and return false even there is a file.

**Comment by jakubmisek** [comment] 2020-12-28 15:03
@jackflyer this might be caused by incorrectly set [Context.RootPath](https://docs.peachpie.io/api/ref/context/#properties). i.e. physical files might be somewhere else than the dotnet application is actually running.

**Comment by jakubmisek** [comment] 2021-06-15 11:46
I'll close the issue. Please create a new one with the code sample for the failing file_exists() operation, preferably with more details like the dump of `<ctx>` variable (`Context`). Thank you

**Closed by jakubmisek** 2021-06-15 11:46 UTC

**Comment by daleffe** [comment] 2023-11-16 13:13
Hi @jakubmisek I did some modifications to the last CodeIginter 2.x version and made it available in [this repository](https://github.com/daleffe/Peachpie.Codeigniter.App), with rewrite for correct routing.
