### ISSUE TITLE
pass by reference not working when using function_exists 

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#569] opened 2019-10-25 17:40 UTC
I just want to share a bug (which probably is not too important, as it's seems to me that the combinations leading to this bug might not be used too often) and a workaround, which worked for us

When using "function_exists" to e.g. add functionality that is available in PHP, but not in PeachPie any call to a c# function that uses PhpAlias to store and change values of this parameter later on will not work if the function is “hidden” by a function_exists clause. See the following example:

	C#
	public bool OCIBindByName (PhpValue statement, PhpValue name, PhpAlias phpValue, PhpValue size, PhpValue strType) 

	PHP
	if (! function_exists('OCIBindByName'))
	{
		function OCIBindByName ($stmt, $name, &$val, $maxLength = -1, $type = SQLT_CHR)
		{
			global $php2oci;
		
			return @$php2oci->OCIBindByName ($stmt, $name, $val, $maxLength, $type);
		}
	}

The PhpAlias will not be handled correctly, so any changes to this PhpAlias (inside or outside the called function) will not be returned to the caller.

Workaround
Nevertheless in case someone has access to the calling code there is a workaround which involves changing the original code. Instead of calling OCIBindByName, someone as to replace this function by new function OCINativeBindByName, which then calls internal PHP function or c# function if the function does not exists. This way the function_exits clause is just around the original PHP function instead of the new c# function. 

	function OCINativeBindByName ($stmt, $name, &$val, $maxLength = -1, $type = SQLT_CHR)
	{
		if (function_exists('OCIBindByName'))
		{
			return @OCIBindByName ($stmt, $name, $val, $maxLength, $type);
		}
		else 
		{
			global $php2oci;
			
			return @$php2oci->OCIBindByName ($stmt, $name, $val, $maxLength, $type);
		}
	}

**Comment by jakubmisek** [comment] 2019-10-26 15:43
This seems to work normally. Just note `OCIBindByName` is a global function so it is not reachable from C# anyways; Only if the function is declared conditionally, then it's .NET name is mangled.

How do you call it from C#? In case of a global function, the correct way is:
```c#
ctx.Call("OCIBindByName", stmt, name, valueAlias, ...);
```

**Comment by jan-ai** [comment] 2019-10-26 18:52
The c# function OCIBindByName was implemented by us as a wrapper to ODP.Net. When we started with PeachPie there was no implementation of OCI available. Does Peachpie natively supports OCI in the meanwhile?

What do you mean with "This seems to work normally". Is it expected that pass by reference does not work when put into an function_exists clause?

**Comment by jakubmisek** [comment] 2019-10-27 13:11
Isn't it related to https://github.com/peachpiecompiler/peachpie/issues/252 ? 

OCI is not implemented yet. Now I get it, I though you are refering to calling from C#.

**Comment by jan-ai** [comment] 2019-10-27 23:35
Probably the root of both problems are the same. A it might be relevant I should also add that the global variable $php2oci comes from 

         public class PhpEnvironment
         {
		private readonly Php2Oci php2Oci;
		…

		public PhpEnvironment (...)
		{
			php2Oci = new Php2Oci ();
			...
		}

		public void SetGlobal (Context ctx)
		{
			ctx.Globals["php2oci"] = PhpValue.FromClass (php2Oci);
			...
		}
		...
         }

from startup.cs

            app.UsePhp (new PhpRequestOptions ()
            {
                BeforeRequest = phpEnvironment.SetGlobal,
		...
            });

and php2oci.cs

	public class Php2Oci
	{
		...
		public bool OCIBindByName (PhpValue statement, PhpValue name, PhpAlias phpValue, PhpValue size, PhpValue strType))
		{
			...
		}
	}

**Comment by jakubmisek** [comment] 2019-10-28 12:00
just to confirm (in short);

this is C#:
```c#
public bool OCIBindByName (PhpValue statement, PhpValue name, PhpAlias phpValue, PhpValue size, PhpValue strType) {
  phpValue.Value = "changed";
}
```

this is the php code:
```php
if (! function_exists('OCIBindByName'))
{
  function OCIBindByName ($stmt, $name, &$val, $maxLength = -1, $type = SQLT_CHR) {
    $something->OCIBindByName($stmt, $name, $val);
  }
}

$val = "unchanged";
OCIBindByName(X, Y, $val);
echo $val;
```

Expected: `changed`
Actual: `unchanged`

**Comment by jakubmisek** [comment] 2019-10-28 12:03
@jan-ai according to #252 this might be caused when $val is originally a variable other than "mixed" (or PhpValue) which should be fixed in https://github.com/peachpiecompiler/peachpie/commit/874376a57367b1b82a5c268107a32faa62e102be

**Comment by jan-ai** [comment] 2019-10-28 18:00
> just to confirm (in short);
> ....
> Expected: changed
> Actual: unchanged

Yes. This looks like the essence of it. 

Just for information: The original value is an element of a PHP array, initialized within PHP with a number (e.g. 38). In fact the value will be changed outside OCIBindByName. but I also tried to change it within OCIBindByName to nail down the problem. And in both cases (within the function and outside) it is currently not working (not changed).

**Comment by jakubmisek** [comment] 2019-10-28 20:52
So you are passing an array element; that is probably the same as #252 . May I ask for the line of code that makes call to the `OCIBindByName` ? thank you

**Comment by jan-ai** [comment] 2019-10-28 22:57
There are two types of code

The first one looks like this and does expect some return value

      foreach($this->output_hash as $key => $size)
      {
        if (in_array ($key, $bindVars))
        {
          @OCINativeBindByName($this->stmt,$key,$this->output_hash[$key],$size);
        }
      }

the second kind of code is simlar to this and does not expect any return values

      foreach($inhash as $key => &$val)
      {
        if (in_array (strtolower($key), $bindVars))
          @OCINativeBindByName($this->stmt,$key,$val,-1);
      }

**Comment by jakubmisek** [comment] 2019-10-29 10:08
@jan-ai thanks! yes the first case is not supported yet but we're working on it. The second case seems to be working already.

I'll close this one as a duplicate of #252, please watch it for any updates :)

**Closed by jakubmisek** 2019-10-29 10:08 UTC
Labels: :question:  question

**Comment by jakubmisek** [comment] 2019-11-07 11:31
Hi @jan-ai - the crucial part of #252 has been fixed, so with latest build your test case should work now

**Comment by jan-ai** [comment] 2019-11-12 23:56
I can confirm that the orignally not working code 

	if (! function_exists('OCIBindByName'))
	{
		function OCIBindByName ($stmt, $name, &$val, $maxLength = -1, $type = SQLT_CHR)
		{
			global $php2oci;
	
			return @$php2oci->OCIBindByName ($stmt, $name, $val, $maxLength, $type);
		}
	}

is now working using peachpie version 0.9.600.

thanks!

**Comment by jakubmisek** [comment] 2019-11-13 10:01
thanks @jan-ai for confirmation
