### ISSUE TITLE
v1.0.0-preview5: "Object reference not set to an instance of an object" in "Peachpie.NET.Core.Sdk.targets" line #245	

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#891] opened 2021-01-12 08:40 UTC
The below error is thrown while trying to build an app:

```
Error		Object reference not set to an instance of an object.
   at Devsense.PHP.Syntax.Parser.AddAliases(Span span, List`1 prefix, Span prefixSpan, List`1 aliases, Boolean isFullyQualified)
   at Devsense.PHP.Syntax.Parser.DoAction(Int32 action)
   at Devsense.PHP.Syntax.ShiftReduceParser`2.Reduce(Int32 rule_nr)
   at Devsense.PHP.Syntax.ShiftReduceParser`2.Parse()
   at Devsense.PHP.Syntax.Parser.Parse(ITokenProvider`2 lexer, INodesFactory`2 astFactory, LanguageFeatures language, IErrorSink`1 errors, IErrorRecovery errorRecovery, Int32 positionShift)
   at Peachpie.CodeAnalysis.Syntax.PhpSourceUnit.Parse(NodesFactory factory, IErrorSink`1 errors, IErrorRecovery recovery, LanguageFeatures features, LexicalStates state)
   at Pchp.CodeAnalysis.PhpSyntaxTree.ParseCode(SourceText sourceText, PhpParseOptions parseOptions, PhpParseOptions scriptParseOptions, String fname)
   at Pchp.CodeAnalysis.CommandLine.PhpCompiler.ParseFile(TextWriter consoleOutput, PhpParseOptions parseOptions, PhpParseOptions scriptParseOptions, Boolean& hadErrors, CommandLineSourceFile file, ErrorLogger errorLogger)
   at Pchp.CodeAnalysis.CommandLine.PhpCompiler.<>c__DisplayClass11_0.<CreateCompilation>b__1(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)	test	C:\.test\nuget\packages\peachpie.net.sdk\1.0.0-preview5\build\Peachpie.NET.Core.Sdk.targets	245	

```

**Comment by jakubmisek** [comment] 2021-01-12 16:04
thanks @menturion 

Will be fixed. It's caused by the trailing comma in the group use statements;
```php
<?php use A\{X,Y,}; // <-- trailing comma
```

**Closed** 2021-01-12 16:18 UTC
Labels: :beetle:  bug

**Comment by menturion** [comment] 2021-01-26 06:28
When will the next preview version be released.?
I am asking this because this reported bug is a blocker for further tests.

**Comment by jakubmisek** [comment] 2021-01-26 13:12
@menturion you can always use the latest build on appveyor nuget feed: 

- versions listed at https://ci.appveyor.com/project/dotnetfoundation/peachpie, the latest one is `1.0.0-appv4505`
- add following NuGet feed https://ci.appveyor.com/nuget/peachpie

e.g. with `NuGet.Config` at the root of your solution:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="peachpie-appveyor" value="https://ci.appveyor.com/nuget/peachpie" />
  </packageSources>
</configuration>
```

---
The quick fix for this issue is to remove the trailing comma in `use` statement:
```php
<?php use A\{X,Y,}; // <-- remove the trailing comma
<?php use A\{X,Y};
```

Anyways; the next official build will be in about 2 weeks

**Comment by menturion** [comment] 2021-01-27 08:42
@jakubmisek 

Thanks for your reply.

I already subscribed to the peachpie appveyor feed in Visual Studio. However, versions later than `v1.0.0-preview5`  (e.g. `1.0.0-appv4509`) were not shown in VS. 

So I will restore the lastest versions (shown here https://ci.appveyor.com/project/dotnetfoundation/peachpie) via CLI.

**Comment by jakubmisek** [comment] 2021-01-27 15:40
@menturion did you check "Prerelease versions"?

![image](https://user-images.githubusercontent.com/842150/106014816-2540f980-60be-11eb-89d2-f401dc20e22c.png)

**Comment by menturion** [comment] 2021-01-27 16:18
@jakubmisek 

Yes, see attached image.
VS is always trying to update to `preview5` and once updated to it later update versions are not shown.

![2021-01-27_170054](https://user-images.githubusercontent.com/41576848/106019953-7ef7f280-60c3-11eb-8d1b-2be92fd35f0b.png)

**Comment by jakubmisek** [comment] 2021-01-27 16:49
of course, it's taking lexicographically highest version ( "p" > "a" )

you have to select the version explicitly .. BUT

to update the compiler and everything, edit the project file:
```xml
<Project Sdk="Peachpie.NET.Sdk/1.0.0-appv4509">
```

Updating just the `Peachpie.App` package won't update the compiler

**Comment by menturion** [comment] 2021-01-27 18:38
`of course, it's taking lexicographically highest version ( "p" > "a" )`

Ok, thanks. I didn't know that.

**Comment by jakubmisek** [comment] 2021-01-27 21:29
me neither!
