### ISSUE TITLE
Media permissions error on "Gutenberg" block editor

### ISSUE THREAD

**Issue by DevJohnC** [peachpiecompiler/peachpie#346] opened 2019-01-11 02:04 UTC
When creating or editing a post with WP 5.x the new block editor is used by default.

If you try to embed an image or desire to set the feature image for the post WordPress will tell you that you 
 lack the requisite permissions - even if you're admin/super admin and can upload images to the media page.

I haven't been able to track it down myself but I suspect that wp_json_encode (and so possibly PeachPie's json_encode implementation) is at fault because the rest-api json payloads embedded into the new post's page looks suspiciously malformed:

`"OPTIONS":{"\/wp\/v2\/media":{"body":{"namespace":"","methods":[1,1],"endpoints":`

The extra slashes don't look like they belong here.

Whether or not it's the root cause I don't know.

**Comment by crbrz** [comment] 2019-01-11 12:34
This is caused by the same issue described in #345. The rest-api server in Wordpress keeps an array with all the registered routes. After a copy of the array is changed the original is affected as well and leads to wrong data in json payloads used to initialize the block editor.

This bit `"\/wp\/v2\/media"` is fine, it's just escaped forward slashed but `methods":[1,1]` should be `"methods":["GET","POST"]`

**Comment by jakubmisek** [comment] 2019-01-11 12:44
Right, this is caused by https://github.com/peachpiecompiler/peachpie/issues/345
We have already work-around on https://github.com/iolevel/wpdotnet-sdk until it will be fixed.

**Closed by jakubmisek** 2019-01-11 12:44 UTC

**Comment by DevJohnC** [comment] 2019-01-11 17:20
> We have already work-around on https://github.com/iolevel/wpdotnet-sdk until it will be fixed.

Can you be more specific please and provide some details about this workaround? I maintain a private build of WordPress on PeachPie.

**Comment by jakubmisek** [comment] 2019-08-06 15:46
fixed in compiler in https://github.com/peachpiecompiler/peachpie/commit/56f591c9ef733dd4f5865e6528bbe308ad726cfa
