### ISSUE TITLE
fastcgi_finish_request doesn't end the HTTP response

### ISSUE THREAD

**Issue by oferns** [peachpiecompiler/peachpie#737] opened 2020-05-01 08:17 UTC
Hi,
I'm porting Open Web Analytics to a .NET 5 (preview) process. Its all working nicely except for one thing, and maybe I am misunderstanding something but the following code does not end the http response as I would expect it to under PHP/PeachPie

```
ob_flush();
flush();
ob_end_flush();
```

I would expect this code to flush the response buffer and end the connection, but it doesn't. There is some more code to run after this (a sort of fire-and-forget) but the server is keeping the connection open until that code has finished running. Am I missing something?
Thanks,
O

**Comment by oferns** [comment] 2020-05-01 08:31
Ah! Any idea when this might be implemented? :)
```


        /// <summary>
        /// This function flushes all response data to the client and finishes the request.
        /// This allows for time consuming tasks to be performed without leaving the connection to the client open.
        /// </summary>
        public static bool fastcgi_finish_request(Context ctx)
        {
            var webctx = ctx.HttpPhpContext;
            if (webctx != null)
            {
                webctx.Flush();

                // TODO: finish the request

                return true;
            }
            else
            {
                return false;
            }
        }
```

**Comment by jakubmisek** [comment] 2020-05-01 12:27
Hi, as I understand it `ob_end_flush()` should flush and stop output buffering, so this function works probably correctly?

So the issue is actually the `fastcgi_finish_request()` which suppose to end the request?

**Comment by oferns** [comment] 2020-05-01 12:42
Yes sorry...My mistake. Ive just forked the repository. Perhaps you could help me actually referencing the SDK so I can debug it? I cannot workout what to replace this bit with

`<Project Sdk="Peachpie.NET.Sdk/0.9.970">`

So that it references my local version and not the nuget package..

**Comment by jakubmisek** [comment] 2020-05-01 12:50
good, the method Flush() needs additional argument `(bool endrequest)` and process it in asp.net and asp.net core accordingly

guide to develop from sources is at https://github.com/peachpiecompiler/peachpie/blob/master/docs/Building-Peachpie.md#developing-with-peachpie-from-sources I hope it helps :)

**Comment by oferns** [comment] 2020-05-01 12:56
Awesome. Thank you very much. Are you amenable to Pull Requests?

**Comment by bfistein** [comment] 2020-05-01 12:57
Of course!

**Comment by jakubmisek** [comment] 2020-05-01 22:26
Would this work? I'm still not sure about ending response in asp.net core

https://github.com/peachpiecompiler/peachpie/tree/feature/fastcgi_finish_request

It makes use of [`HttpContext.Abort()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.abort?view=aspnetcore-3.1) which ends connection to client

**Comment by oferns** [comment] 2020-05-02 18:05
Hi,

Im trying to test the fastcgi_finish_request of v1.0.0-dev but I am consistently getting this error (in either master branch or the fastcgi_finish_request branch) before I hit the call to fastcgi_finish_request. The 0.9.970 version still works. Here's the stack...Im still trying to work it out... 


`▶ | CustomAttributes | 't.CustomAttributes' threw an exception of type 'System.MissingMethodException' | System.Collections.Generic.IEnumerable<System.Reflection.CustomAttributeData> {System.MissingMethodException}

`

```
System.TypeInitializationException: The type initializer for 'Pchp.Core.Reflection.TypeInfoHolder`1' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void Pchp.Core.PhpTypeAttribute..ctor(System.String, System.String, Byte)'.
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element, Boolean inherit)
   at Pchp.Core.Reflection.PhpTypeInfo.GetPhpTypeAttribute()
   at Pchp.Core.Reflection.PhpTypeInfo..ctor(Type t)
   at Pchp.Core.Reflection.TypeInfoHolder`1..cctor()
   --- End of inner exception stack trace ---
   at Pchp.Core.Context.DeclareType[T]()
   at <Root>.owa_lib_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in D:\repos\vsnet\VS.OWA\owa_lib.php:line 34
   at <Root>.owa_lib_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.log_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in D:\repos\vsnet\VS.OWA\log.php:line 20
   at <Root>.log_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext _, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jakubmisek** [comment] 2020-05-02 18:34
You have to change all the references to `1.0.0-dev`. Make sure there is nothing referring to `0.9.970` anymore.

This error is caused by runtime not expecting assembly compiled with old (0.9.970) compiler.

**Comment by oferns** [comment] 2020-05-02 18:34
I suspect there was some DLL mixing going on there so I have cleaned and rebuilt everything and now I am getting "Multiple references to the same array instance!" exceptions consistently.

**Comment by oferns** [comment] 2020-05-02 18:36
sorry we must have posted at the same time. I am hitting this exception. The PHPValue is "base"...

**Comment by jakubmisek** [comment] 2020-05-02 18:37
```
Multiple references to the same array instance!
```
is caused during variable serialization - seems the variable contains the same array object twice, but not properly referenced in PHP manner. Is it possible the serialized variable was created in C# and passed to PHP code?

**Comment by jakubmisek** [comment] 2020-05-02 18:37
Not sure what  `The PHPValue is "base"...` means

**Comment by oferns** [comment] 2020-05-02 18:39
Sorry. I hit reply to early.

**Comment by oferns** [comment] 2020-05-02 18:40
This is not a great medium for chat!

**Comment by oferns** [comment] 2020-05-02 18:41
Heres the stack

`   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.Accept(PhpArray value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptArrayItem(KeyValuePair`2 entry)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpArray obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.Accept(PhpArray value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptArrayItem(KeyValuePair`2 entry)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpArray obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.Accept(PhpArray value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpValue obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObjectProperties(IEnumerable`1 properties)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.SerializeObject(Object obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObject(Object value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptArrayItem(KeyValuePair`2 entry)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpArray obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.Accept(PhpArray value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpValue obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObjectProperties(IEnumerable`1 properties)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.SerializeObject(Object obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObject(Object value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpValue obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObjectProperties(IEnumerable`1 properties)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.SerializeObject(Object obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObject(Object value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Core.PhpVariableVisitor.Accept(PhpValue obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObjectProperties(IEnumerable`1 properties)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.SerializeObject(Object obj)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.AcceptObject(Object value)
   at Pchp.Core.PhpValue.Accept(PhpVariableVisitor visitor)
   at Pchp.Library.PhpSerialization.PhpSerializer.ObjectWriter.Serialize(Context ctx, PhpValue variable, RuntimeTypeHandle caller)
   at Pchp.Library.PhpSerialization.PhpSerializer.CommonSerialize(Context ctx, PhpValue variable, RuntimeTypeHandle caller)
   at Pchp.Library.PhpSerialization.Serializer.Serialize(Context ctx, PhpValue variable, RuntimeTypeHandle caller)
   at Pchp.Library.PhpSerialization.serialize(Context ctx, RuntimeTypeHandle caller, PhpValue value)
   at Console.logMemory(PhpValue object, PhpValue name) in D:\repos\vsnet\VS.OWA\includes\pqp\classes\Console.php:line 37
   at owa_coreAPI.profile(Context <ctx>, PhpValue that, PhpValue function, PhpValue line, PhpValue msg) in D:\repos\vsnet\VS.OWA\owa_coreAPI.php:line 1369
   at owa_db_mysql.query(PhpValue sql) in D:\repos\vsnet\VS.OWA\plugins\db\owa_db_mysql.php:line 161
   at owa_db_mysql.connect() in D:\repos\vsnet\VS.OWA\plugins\db\owa_db_mysql.php:line 132
   at owa_db_mysql.prepare(PhpValue string) in D:\repos\vsnet\VS.OWA\plugins\db\owa_db_mysql.php:line 273
   at owa_db._makeConstraintClause(PhpValue type, PhpValue params) in D:\repos\vsnet\VS.OWA\owa_db.php:line 603
   at owa_db._makeWhereClause() in D:\repos\vsnet\ 	9.16s		
`

**Comment by jakubmisek** [comment] 2020-05-02 18:42
It works in 0.9.970 because it is DEBUG assert, 0.9.970 is built in Release configuration.

**Comment by jakubmisek** [comment] 2020-05-02 18:44
although it is not relevant to this issue, you may commend the Debug.Assert to proceed

**Comment by oferns** [comment] 2020-05-02 18:45
I really should have thought of that. Sorry. I will build it in release mode.

**Comment by jakubmisek** [comment] 2020-05-02 18:47
building in release is not exactly the solution :)) but one more time
```
Multiple references to the same array instance!
```
is caused during variable serialization (your call to `serialize()` function) - the value `name` you pass in contains the same instance of PhpArray more than once. This assertion will be ignored in next update

**Comment by oferns** [comment] 2020-05-02 18:49
Yeah my brain is clearly in weekend mode. As i said, I am porting Open Web Analytics and as such did not write any of the PHP code. Thank you for the pointers though.. That makes sense. Ive already made a couple of PRs on the OWA repo cleaning up the PHP errors highlighted by PeachPie. Guess there will be a couple more!

**Comment by jakubmisek** [comment] 2020-05-02 18:52
great!

So is [`HttpContext.Abort()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.abort?view=aspnetcore-3.1) a good implementation for `fastcgi_finish_request()` ?

**Comment by oferns** [comment] 2020-05-02 18:53
Gimme 10 Ill tell ya!

**Comment by jakubmisek** [comment] 2020-05-02 18:55
thanks! because based on specification, this can be only implemented in old aspnet ... not so easy in aspnetcore

**Comment by oferns** [comment] 2020-05-02 19:10
Ok so it does allow the code to continue to run after the abort, but it produces an error on the client (which isnt unexpected I suppose). So it *sort of works.

Ideally we need to return from the PhpHandlerMiddleware and not call the next delegate and that will naturally end the response in ASP.NET Core. I don't know how though. I thought if we could  make RequestContextCore.ProcessScript return a Task then possibly we could use TaskCompletionSource to trigger that response but carry on execution...

**Comment by jakubmisek** [comment] 2020-05-02 19:14
There is HttpContext.RequestAborted cancellation token which might be used. Anyways; we don't call the next delegate once the request.

What about closing the underlying response stream? would it work?

**Comment by oferns** [comment] 2020-05-02 19:30
As I understand it, the  CancellationToken is for notifying you if the request is cancelled by the client. You cant actually cancel it yourself without registering a cancellation source. Im not sure but I think I might be able to do this with a combination of task.run and a TaskCompletionSource. Ill let you know how I get on

**Comment by jakubmisek** [comment] 2020-05-02 19:30
yes, CancellationToken can be used by you to not call the next delegate

**Comment by oferns** [comment] 2020-05-02 20:42
Hi, there's a PR here
https://github.com/peachpiecompiler/peachpie/pull/740

cheers
O

**Comment by oferns** [comment] 2020-05-03 11:47
Ive updated the PR so that the context and the ProcessScript call are on the same thread. Ive also added a little bit of code to call FinalizeBufferedOutput() from RequestContextCore which meant changing its access level from internal to protected. It also meant adding a private field to Context to make sure FinalizeBufferedOutput() is only called once.

**Closed** 2020-05-07 12:57 UTC
