### ISSUE TITLE
error happens when i use local builded 1.0.0-dev package

### ISSUE THREAD

**Issue by vvtll** [peachpiecompiler/peachpie#1012] opened 2022-01-09 14:42 UTC
```
Process terminated. Assertion Failed
   at Pchp.Core.Context.AutoloadByTypeNameFromClassMap(String fullName, Boolean onlyAllowed)
   at Pchp.Core.Context.ImplicitAutoloadTypeByName(String fullName)
   at Pchp.Core.Context.Pchp.Core.IPhpAutoloadService.AutoloadTypeByName(String fullName)
   at Pchp.Core.Context.GetDeclaredType(String name, Boolean autoload)
   at Pchp.Library.Objects.class_exists(Context ctx, String class_name, Boolean autoload)
   at Pchp.Library.Objects.class_exists(Context ctx, String class_name)
```

**Comment by vvtll** [comment] 2022-01-09 14:45
But  when I use 1.0.10 online nuget version,there is all right.Is there any wrong action for me!I only use "dotnet build" command on ubuntu for build the local develop package.

**Comment by jakubmisek** [comment] 2022-01-09 14:52
This is simply caused by using the `-dev` package - which is compiled in Debug configuration hence it has all the Debug Assertions enabled.

Version on NuGet is compiled in Release configuration, without debug assertions.

Anyways; this failure is caused by a bug in the runtime - `class_exists()` should normalize class names and trim off any leading backslash `"\"` characters internally - will be fixed!

**Comment by vvtll** [comment] 2022-01-09 14:59
Oh,I know the reason,thanks,but is there any way to publish release local package for develop

**Comment by jakubmisek** [comment] 2022-01-09 15:01
> Oh,I know the reason,thanks,but is there any way to publish release local package for develop

yes, build the PeachPie project in Release configuration:

```
dotnet build -c Release
```

**Closed** 2022-01-09 15:00 UTC

**Comment by vvtll** [comment] 2022-01-09 15:03
It is well,thanks very much!
