### ISSUE TITLE
Wordpress(?) over-committing memory

### ISSUE THREAD

**Issue by DevJohnC** [peachpiecompiler/peachpie#348] opened 2019-01-18 00:22 UTC
We have peachpie running a Wordpress network which keeps getting killed by the linux out-of-memory process killer.

```
[31346.098815] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[31346.315298] [20856]     0 20856  2098347   433262    1184       9        0          1000 dotnet
[31346.338398] Out of memory: Kill process 20856 (dotnet) score 1845 or sacrifice child
[31346.345205] Killed process 20856 (dotnet) total-vm:8393388kB, anon-rss:1733048kB, file-rss:0kB
```

The `dotnet` process (which is a Peachpie project) is reserving a lot more memory than it's actually using.

Are there tuning options to mitigate this situation?

**Comment by jakubmisek** [comment] 2019-01-19 15:41
Can this be related to https://github.com/aspnet/AspNetCore/issues/3409 ?

**Comment by DevJohnC** [comment] 2019-01-20 22:16
Disabling the server-gc seems to have bought us a modicum of stability but it doesn't last. We also turned off the wp cron.

We still experience the same issue: after running for around half an hour with a steady flow of traffic the `dotnet` process spikes to 100% cpu usage and keeps allocating memory until the OOM killer finally kills the process and allows the node to restabalize.

**Comment by DevJohnC** [comment] 2019-01-21 22:55
To further add to this issue, I watched the issue happen in real-time today to try and get more details and see if it pinged anything in your minds.

* We're on a pretty vanilla WordPress install - we have some basic themes and configured as a network with no plugins besides some filters to set comment options and filter admin menus
* Traffic levels are not high but are consistent, it's normal that the app is serving a web request constantly
* Traffic logs show nothing suspicious and a replay of web requests leading up to the issue doesn't reproduce it
* The issue occurs at oddly specific timing, around 30-40mins of uptime each occurrence
* Server death looks like this:
  * CPU usage spikes to 100% user-mode usage
  * This gradually becomes more and more kernel-mode cpu usage, staying at 100% utilization overall
  * During this time memory usage (which resides at just under 500MB usually) starts spiking by GBs at a time, quickly assigning then deleting GBs of RAM
  * This continues until the server becomes unresponsive, likely due to the CPU giving more and more time to kernel-mode operations
  * During this time the database is not showing a high data throughput, meaning the GBs of memory assigned and deleted aren't database records

Given the timing nature and how the CPU just becomes consumed in kernel-mode it feels like a deadlock issue? Or something related? Peachpie seems to just stall waiting for whatever kernel operation is happening to complete. Perhaps some sort of internal cache that deadlocks when there's continuous requests incoming?

**Comment by jakubmisek** [comment] 2019-01-22 12:36
I'm still thinking of some Linux specific .NET Core issue. (We're running tens of WordPress websites on .NET Core on Win10 x64 and Azure and the servers are stable for months so far, using 400-600 MB of RAM). Using  the default setup https://github.com/iolevel/wpdotnet-sdk/blob/master/app/Program.cs

Anyways; it is possible there is a dead-loop in the PeachPie code ... in that case it would be great if you'd be able to debug the process? Or attach when this happens? Is it possible on Linux ?

**Comment by jakubmisek** [comment] 2019-01-23 11:18
It seems like it might be caused by a plugin that we didn't test yet ..

Anyways; in Visual Studio there is *Mini dump* or actually if you'd have a chance to see stack trace where the OOM happens, that might help too.

**Comment by jakubmisek** [comment] 2019-01-25 15:44
@DevJohnC both are possible - however I was not able to replicate the issue (on Win x64). `formatting.php` file is definitely an ugly piece of code but seems to not cause any issues. When profiling performance it is not even reported as a significant function

![image](https://user-images.githubusercontent.com/842150/51756002-48480580-20c0-11e9-8aa7-4c2d55a0f834.png)
_(no formatting.php)_

**Comment by jakubmisek** [comment] 2019-01-25 17:46
Is it possible for you to run the web site locally?
Do you have list of your enabled wp plugins ?

**Comment by jakubmisek** [comment] 2019-04-15 09:50
So far we cannot repro the issue with memory. (but we are running Windows servers).

We are constantly requesting RSS2 feed and nothing weird happens yet.

**Comment by jakubmisek** [comment] 2019-04-21 07:40
closing for now, if you'd have any more details, please comment :) thank you!

**Closed by jakubmisek** 2019-04-21 07:40 UTC
