### ISSUE TITLE
array content gets "overwritten"

### ISSUE THREAD

**Issue by jan-ai** [peachpiecompiler/peachpie#573] opened 2019-11-03 18:20 UTC
Using the following code all elements of the array $pds gets set to false (debugger is showing &false) as soon as the second loop is reached. Also the debugger is (unexpectingly) showing that the array elements are set as reference values (see below). 

I guess because $pd is used twice within this function and the second time as a reference to array elements, it will be used as reference at the first loop already. As soon as the second loop gets reached/initialized $pd is set to false and all elements of the array are then set to false as well. But that's only a guess. Renaming $pd to $pd1 for the first loop "solves" the problem.

```php
$pds = array();

while($pd = $db->fetchResult()) {
	array_push($pds, $pd);
}

foreach ($pds as $idx => &$pd) {
		...
}
```

the array `$pds` lools like 

	pds
		value
			[0]      &array(length=6)
			[1]      &array(length=6)
			…

before the second loop is reached. I would not expect the & before array. 

And it looks like the following when secode loop is reached:

	pds
		value
			[0]      &false
			[1]      &false
			…

let me know if more Information is needed.

**Comment by jakubmisek** [comment] 2019-11-04 18:21
Does the function have some parameters?

**Comment by jan-ai** [comment] 2019-11-04 22:39
fetchResult looks like

	function FetchResult($resflag = OCI_ASSOC,$extstmt = -1)
	{
		...
		$res = @oci_fetch_array($mystate, $resflag+OCI_RETURN_NULLS+OCI_RETURN_LOBS);
		...
		if ($res === false)
		{
			$res = null;
		}
		...
		return($res);
	}

oci_fetch_array looks like

	if (! function_exists('oci_fetch_array'))
	{
		function oci_fetch_array ($stmt, $mode = OCI_BOTH)
		{
			global $php2oci;
	
			return @$php2oci->oci_fetch_array ($stmt, $mode);
		}
	}

and php2oci->oci_fetch_array …

	public PhpValue oci_fetch_array (PhpOracleStatement statement, string mode)
	{
		PhpArray resArr = new PhpArray ();

		if (!statement.Reader.Read ())
		{
			return PhpValue.False;
		}

		for (int i = 0; i < statement.Reader.FieldCount; i++)
		{
			dynamic value = statement.Reader.GetValue (i);
			PhpValue phpValue;

			switch (value)
			{
				...
				case short sValue:
					phpValue = PhpValue.Create ((long) sValue);
					break;
				...
			}
			resArr[statement.Reader.GetName (i)] = phpValue;
		}

		return PhpValue.Create (resArr);
	}

**Comment by jakubmisek** [comment] 2019-11-07 12:09
thanks does the function with `$pds` variable have some parameters?

**Comment by jan-ai** [comment] 2019-11-07 13:23
All functions are shown as they are used in our code. What function do you mean in detail with "function with $pds", as $pds is an array?

**Comment by jakubmisek** [comment] 2019-11-07 14:19
when you say that `$pds` is not shown correctly in debugger, it may be caused by having another `$pds` in the function's context. Usually when there is `$pds` parameter with a type hint.

How does the header of the containing function look like?

**Comment by jan-ai** [comment] 2019-11-07 14:40
Now I understand. $pds is part of a php script and not "encapsulated" in function. I've searched the whole project and luckily I couldn't find any other usage of $pds then those 3 shown above (as the php script includes a lot of other files as well).

**Comment by jakubmisek** [comment] 2019-11-07 14:48
so `$pds` is a global variable?

**Comment by jan-ai** [comment] 2019-11-07 16:36
There is no global keyword, but as there is no function around $pds it seems to be a global variable.

**Comment by jakubmisek** [comment] 2019-12-04 15:31
so after
```php
while($pd = $db->fetchResult()) {
	array_push($pds, $pd);
}
```
the `$pd` array contains reference?

**Comment by jakubmisek** [comment] 2020-01-07 13:46
it might be caused by our bug in `array_push`:
```php
    $arr = [];
    $c = &$a;
    array_push($arr, $c); // <-- reference to $c is kept!
    $c = 666;
```

will be fixed

**Comment by jakubmisek** [comment] 2020-01-07 14:18
@jan-ai please check if the issue has been resolved.

**Comment by jan-ai** [comment] 2020-01-09 00:46
I tried Version 0.9.800 of peachpie. The array looks good now before the second loop (no & before array; see example below (second element)). Also the array keeps its data when the second loop starts (see first element). => So looks good to me. 

Only point to mention is that the elements of the array change from array(length = 6) to &array(length =6), while loop is running. Which I guess might be nessecary because of the structure of the second loop.

  | Name | Wert | Typ
-- | -- | -- | --
◢ | Value | array(length = 33) | array
  | ▶ [0] | &array(length = 6) | integer => array
  | ▶ [1] | array(length = 6) | integer => array
  |...

**Comment by jakubmisek** [comment] 2020-01-09 13:07
Thank you, the latest build on appveyor (nuget feed https://ci.appveyor.com/nuget/peachpie) fixes `array_push` as well, if it makes any difference.

Closing the issue

**Closed by jakubmisek** 2020-01-09 13:07 UTC
