### ISSUE TITLE
class_exists doesn't work with the new build-in autoloading

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#747] opened 2020-05-07 17:15 UTC
Sample (in the context of PHPUnit):

```php
if (!class_exists("PHPUnit\\TextUI\\ResultPrinter")) {
    echo "0";
} else {
    echo "1";
}

if (!class_exists(PHPUnit\TextUI\ResultPrinter::class)) {
    echo "0";
} else {
    echo "1";
}

$instance = new PHPUnit\TextUI\ResultPrinter();

if (!class_exists("PHPUnit\\TextUI\\ResultPrinter")) {
    echo "0";
} else {
    echo "1";
}

if (!class_exists(PHPUnit\TextUI\ResultPrinter::class)) {
    echo "0";
} else {
    echo "1";
}
```

PHP Output (when using the composer autoloader):
```
1111
```

PeachPie output:
```
0000
```

Even though it does initiate the instance of ResultPrinter. So it does find the class.

**Comment by jakubmisek** [comment] 2020-05-07 17:28
Is it in a phar content?

**Comment by calvinbaart** [comment] 2020-05-07 18:06
No, both the sample file and the file that ResultPrinter is in are in a vendor folder in the same project

**Comment by jakubmisek** [comment] 2020-05-07 19:17
May I ask for a small sample project? It works on my examples.

**Comment by calvinbaart** [comment] 2020-05-07 20:26
Made a sample project here: https://github.com/calvinbaart/bug-sample-peachpie-class-exists

**Comment by jakubmisek** [comment] 2020-05-07 22:06
thank you!

**Comment by jakubmisek** [comment] 2020-05-08 14:29
`vendor/autoload.php` does not have to be included?

**Comment by calvinbaart** [comment] 2020-05-08 15:57
I was trying to see if I can keep it out. I can create an instance of the classes without including the auto loader but class_exists returns false anyway

**Comment by jakubmisek** [comment] 2020-05-08 19:37
when running this sample on PHP:
```
00
Error: Class 'PHPUnit\TextUI\ResultPrinter' not found
```

When running on Peachpie:
`0000` (there is a bug it does not call autoloader or not throw an exception - will be fixed)

to enable the new autoloading, it has to be specified in the root `composer.json` `"autiload"` patterns

**Comment by jakubmisek** [comment] 2020-05-08 19:48
Basically, if there is no `"autoload"` section in root `composer.json`, the behavior is unchanged. 
To take advantage of autoloading vendor packages as well (which all have its own `composer.json`) they suppose to be compiled separately (referenced as ProjectReference or PackageReference), or you'd have to fill the `autoload` section with all the possible rules. 

The bug in this issue is caused by missing check for the class not being autoloaded.

**Closed** 2020-05-08 19:48 UTC
Labels: :beetle:  bug
