### ISSUE TITLE
Parsing PHP in C#

### ISSUE THREAD

**Issue by ajhalls** [peachpiecompiler/peachpie#874] opened 2020-10-23 21:49 UTC
I booted up a fresh Laravel 8 installation and usign the php function `get_included_files()` shows that it loads up 611 files to display the dashboard. To me that is crazy. I want to tokenize the entire vendor folder, store it in a database, find which functions are actually being used, throw them into a single file and be done with it. Ok... so I skipped a couple steps, but really, not that many.

I have a pretty decent start using regular expressions (https://stackoverflow.com/questions/64491839/regex-php-function), but everyone always recommends using a tokenizer, so I am trying.

Here is PHP-Parser: https://github.com/nikic/PHP-Parser/tree/master/lib/PhpParser/Parser, I got it to compile to a DLL and load in my C# application, but not sure how to follow their basic example:

```php
$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
try {
    $ast = $parser->parse($code);
} catch (Error $error) {
    echo "Parse error: {$error->getMessage()}\n";
    return;
}

$dumper = new NodeDumper;
echo $dumper->dump($ast) . "\n";
```
I am not sure how to translate that into C# using PeachPie. When using Intellisense I can get the following sections to show up without error messages:
```c#
Context ctx = Context.CreateConsole(null);
PhpParser.ParserFactory parser = new ParserFactory(ctx);
parser.create(1, null, null);
NodeDumper dumper = new NodeDumper(ctx, null);
```
Obviously there are too many `null` references, but it doesn't let me do anything like `ParserFactory::PREFER_PHP7` and can't find the `parse()` function at all.  I haven't ever worked with either of these two applications, so learning as I go.

**Comment by jakubmisek** [comment] 2020-10-23 22:21
I would recommend using the PeachPie/Roslyn API, because the compiler is a parser as well:

In your C# project, add reference to `Peachpie.CodeAnalysis` and use the following snippet to parse the code:

```c#
var tree = PhpSyntaxTree.ParseCode(
  SourceText.From(code, Encoding.UTF8),
  PhpParseOptions.Default,
  PhpParseOptions.Default,
  path);
```

---

If you still want to use the `ParserFactory`, the problem is, it sometimes misses type hints, so for example `parser.create` returns a value of type `PhpValue`, instead of `Node`.

In this case, you have to cast it to the correct type:

```c#
using var ctx = Context.CreateConsole("program.cs");
var parserfactory = new ParserFactory(ctx);
var parser = parserfactory.create(ParserFactory.PREFER_PHP7, null, PhpArray.Empty); // 3rd parameter cannot be null
var ast = parser.parse(code).Cast<Node>(); // convert PhpValue -> Node
```

If you'd have a stack trace or an exception, please post it here so I can give more information.

**Comment by jakubmisek** [comment] 2020-10-26 14:19
I'll close it for now, please comment if you'd have anything.

If you'd have a github repo with your .NET project with PhpParser, I can take a look and update eventually :) 

thanks!

**Closed by jakubmisek** 2020-10-26 14:20 UTC
Labels: :question:  question

**Comment by ajhalls** [comment] 2020-10-27 18:46
I am playing around with your first example using `PhpSyntaxTree`, is there any way to dump that to JSON or something to make it easier to get an overview of what is being retrieved, how it is being stored, so I will know how to interact with it? 

It was quite easy to get it working, thank you, it has a lot more than I need, so trying to narrow down what to focus on.

**Comment by jakubmisek** [comment] 2020-10-28 17:19
In case of `PhpSyntaxTree`, you suppose to extend the class `TreeVisitor`, and pass `PhpSyntaxTree.Root` to it:

```c#
class MyVisitor : TreeVisitor {
 // override Visit ***
}

new MyVisitor().VisitGlobalCode(phpsyntaxtree.Root);
```
