### ISSUE TITLE
Failing to build self-contained executable

### ISSUE THREAD

**Issue by ghost** [peachpiecompiler/peachpie#972] opened 2021-08-04 05:46 UTC
Hi,
Trying to compile a self-contained app, have tried the following combinations:
`dotnet publish -c release --runtime linux-x64`
`dotnet publish -c release -r linux-x64`
`dotnet publish -c release --self-contained -r linux-x64`

In each case, on running, the following is printed:

```
Cannot use file stream for [/home/user/build/console.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/usr/share/dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/user/build/console.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/home/user/build/console.runtimeconfig.json' file and specify the appropriate framework.
```

In case it's of any relevance, I'm using the .NET Framework 5.0 and VS Code

**Comment by jakubmisek** [comment] 2021-08-04 07:27
Hi,

This seems like the same issues as on https://stackoverflow.com/questions/47285243/a-fatal-error-was-encountered-the-library-libhostpolicy-so-required or https://github.com/aspnet/aspnet-docker/issues/301

- does `libhostpolicy.so` exist in `/usr/share/dotnet` ?
- do you have `appsettings.json` with the correct letter casing?
- ensure there is `<OutputType>Exe</OutputType>` in the project file (http://szahariev.blogspot.com/2016/10/libhostpolicyso-was-not-found-error.html)

**Comment by jakubmisek** [comment] 2021-09-24 15:42
closing as it is most likely caused by the .NET configuration documented on the links above

**Closed by jakubmisek** 2021-09-24 15:42 UTC
