### ISSUE TITLE
[Question] Loader Exceptions

### ISSUE THREAD

**Issue by menturion** [peachpiecompiler/peachpie#378] opened 2019-03-18 09:06 UTC
While trying to debug the compiled app within VS2017 the following Loader Exceptions are shown on startup. I think that these exceptions are not thrown due to an issue of PeachPie. 

How to deal with these exceptions? Do I have to load additional NuGet packages? 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'DllLoader`1' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
```
Method 'toRgb' in type 'BaconQrCode.Renderer.Color.Alpha' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'toRgb' in type 'BaconQrCode.Renderer.Color.Cmyk' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'toRgb' in type 'BaconQrCode.Renderer.Color.Gray' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'toRgb' in type 'BaconQrCode.Renderer.Color.Rgb' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getExternalPath' in type 'BaconQrCode.Renderer.Eye.CompositeEye' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getExternalPath' in type 'BaconQrCode.Renderer.Eye.ModuleEye' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getExternalPath' in type 'BaconQrCode.Renderer.Eye.SimpleCircleEye' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getExternalPath' in type 'BaconQrCode.Renderer.Eye.SquareEye' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'render' in type 'BaconQrCode.Renderer.ImageRenderer' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'scale' in type 'BaconQrCode.Renderer.Image.EpsImageBackEnd' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'scale' in type 'BaconQrCode.Renderer.Image.ImagickImageBackEnd' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'scale' in type 'BaconQrCode.Renderer.Image.SvgImageBackEnd' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'createPath' in type 'BaconQrCode.Renderer.Module.DotsModule' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'createPath' in type 'BaconQrCode.Renderer.Module.RoundnessModule' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'createPath' in type 'BaconQrCode.Renderer.Module.SquareModule' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'translate' in type 'BaconQrCode.Renderer.Path.Close' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'translate' in type 'BaconQrCode.Renderer.Path.Curve' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'translate' in type 'BaconQrCode.Renderer.Path.EllipticArc' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'translate' in type 'BaconQrCode.Renderer.Path.Line' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'translate' in type 'BaconQrCode.Renderer.Path.Move' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'render' in type 'BaconQrCode.Renderer.PlainTextRenderer' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'then' in type 'GuzzleHttp.Promise.Coroutine' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'addTimer' in type 'React.EventLoop.ExtLibevLoop' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'addTimer' in type 'React.EventLoop.StreamSelectLoop' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getInterval' in type 'React.EventLoop.Timer.Timer' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'connect' in type 'React.Socket.Connector' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'connect' in type 'React.Socket.DnsConnector' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'connect' in type 'React.Socket.SecureConnector' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getAddress' in type 'React.Socket.SecureServer' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getAddress' in type 'React.Socket.Server' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'connect' in type 'React.Socket.TcpConnector' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getAddress' in type 'React.Socket.TcpServer' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'connect' in type 'React.Socket.TimeoutConnector' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'connect' in type 'React.Socket.UnixConnector' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getAddress' in type 'React.Socket.UnixServer' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'isReadable' in type 'React.Stream.CompositeStream' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'isReadable' in type 'React.Stream.DuplexResourceStream' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'isReadable' in type 'React.Stream.ThroughStream' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'isWritable' in type 'React.Stream.WritableResourceStream' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getName' in type 'Symfony.Component.HttpFoundation.Session.SessionBagProxy' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getKey' in type 'Zend.Cache.Psr.CacheItemPool.CacheItem#2' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getKey' in type 'Zend.Cache.Psr.CacheItemPool.CacheItem#1' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method '__invoke' in type 'Zend.ServiceManager.Proxy.LazyServiceFactory' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'get' in type 'Zend.ServiceManager.PsrContainerDecorator' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'getData' in type 'Zend.Stdlib.ArrayUtils.MergeReplaceKey' from assembly 'testapp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by jakubmisek** [comment] 2019-03-18 09:58
This is incorrectly compiled code, definitely caused by the PeachPie compiler.

What version is it? We have fixed something related on Mar 16, 2019

**Comment by menturion** [comment] 2019-03-18 10:05
The "msbuildproj" looke like this:

```
<Project Sdk="Peachpie.NET.Sdk/1.0.0-appv2342">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>cknsys</AssemblyName>
    <NoWarn>PHP5006,PHP5008,PHP5010,PHP5011,PHP5012,PHP5014,PHP5015,PHP5018,PHP0125</NoWarn>
  </PropertyGroup>

  ...
  
  
  <ItemGroup>
    <Content Include="**" Exclude="obj/**;bin/**;PublishProfiles/**;@(Compile);$(MsBuildThisFile)">
      <PackagePath>contentFiles/any/netcoreapp2.0/wwwroot/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToOutputDirectory>true</CopyToOutputDirectory>
      <CopyToPublishDirectory>true</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by jakubmisek** [comment] 2019-03-18 10:27
thanks, found the bug (caused by very recent compiler optimization)
```php
<?php
interface SessionBagInterface {
    public function getName();
}

final class SessionBagProxy implements SessionBagInterface {
    public function getName() {
        return $this->bag->getName();
    }
}
```

**Comment by jakubmisek** [comment] 2019-03-18 10:38
should be fixed in https://github.com/peachpiecompiler/peachpie/commit/7c47383f66c3748d60186bbd3fcc6b3bf0fd452f

`1.0.0-appv2343`

**Closed by jakubmisek** 2019-03-18 10:38 UTC

**Comment by menturion** [comment] 2019-03-18 11:19
Many thanks.
Updated, rebuilt ... and it works :) 

Off topic: 
The app would need the Locale class, i.e. PECL intl (s. http://php.net/manual/de/class.locale.php). 
The Locale class seems not to be covered by PeachPie yet(?). Is there any NuGet package?

**Comment by jakubmisek** [comment] 2019-03-18 12:48
We are planning to support intl https://docs.peachpie.io/php/Compatibility/#implemented-extensions
for now it is not there (not needed yet).

There is built-in support for locales (cultures) in .NET, but the API differs from PHP's locale (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netstandard-2.0)

Depends on what you need, something like this should work:
```
<?php

use System\Globalization\CultureInfo;
$c = new CultureInfo("en-ES");
echo $c->DisplayName;
```

**Comment by menturion** [comment] 2019-03-18 13:35
Many thanks for the info!
I think I have to wait for PeachPie's Intl support. 

I have viewed your list of supported extensions and missed the "Imagick" class (s. http://php.net/manual/de/class.imagick.php) which I use e.g. to create thumbnails of PDF pages or to generate a QR code. If a PHP app wants to provide (OATH OTP) 2factor authentication, it is likely that it requires "Imagick". Maybe you could extend your list by this extension(?).

**Comment by jakubmisek** [comment] 2019-03-18 14:53
`ImageMagick` is also possible. We can even make it fully implemented in .NET without need of installing ImageMagick binaries.. (the goal of PeachPie is to be fully cross-platform without an unsafe native code).

We will probably implement this by ourselves at some point, or a contributor might do it. Otherwise we are providing similar services (as implementing something in advance) commercially (https://build.peachpie.io/)

**Comment by 7starsone** [comment] 2019-09-05 08:09
> `ImageMagick` is also possible. We can even make it fully implemented in .NET without need of installing ImageMagick binaries.. (the goal of PeachPie is to be fully cross-platform without an unsafe native code).
> 
> We will probably implement this by ourselves at some point, or a contributor might do it. Otherwise we are providing similar services (as implementing something in advance) commercially (https://build.peachpie.io/)

Hello, please, does it mean that at the moment there's no way to let ImageMagick work? Eg. my code on local Wamp works as usual, if i import the entire project into Visual Studio/PeachPie it claims about compile errors for ImageMagick....
thanks

**Comment by jakubmisek** [comment] 2019-09-05 09:15
Imagick extension is not implemented in PeachPie, but you can exec Imagick using `exec()`. There should not be any compile errors tho.
