### ISSUE TITLE
[Question] Constructor with no parameters

### ISSUE THREAD

**Issue by jp2masa** [peachpiecompiler/peachpie#259] opened 2018-08-09 00:26 UTC
I don't know any implementation details, so maybe this is not really possible, but I'd like to constructor with no parameters. I created a simple class with no constructor (default constructor), and then with an explicit empty public constructor, then I decompiled the generated assembly with ILSpy, and got this code:
```cs
[PhpFieldsOnlyCtor]
protected internal Kernel(Context <ctx>)
{
    this.<ctx> = <ctx>;
}

public Kernel(Context <ctx>) : this(<ctx>)
{
    this.__construct();
}

public virtual PhpValue __construct()
{
    return PhpValue.Null;
}
```
The constructor takes one parameter, which is stored in a field, which is actually never used.

I also looked at the php-library sample and in fact the constructor needs a `Context`.

I don't know any implementation details, but is this `Context` really important? Would it possible to generate a constructor with no parameters?

**Comment by jakubmisek** [comment] 2018-08-10 13:58
The class is compiled with `.ctor` always requiring `Context` as its parameter. The context is almost always needed (the only exception would be your empty class).

The reason is, every PHP object is bound to Context (representing PHP's thread/request/application) and internally it requires it to perform most of the operations.

In this case, we can only "improve" the compiler so it won't create two `.ctor`s.

If using it from C#, you can create new `Context` and pass it to the .ctor

**Comment by jp2masa** [comment] 2018-08-10 14:39
> The context is almost always needed (the only exception would be your empty class).

The class is not empty, but I understand that probably many PHP features rely on that.

> The reason is, every PHP object is bound to Context (representing PHP's thread/request/application)

Maybe it could be static? There's only one application, threads can be managed using the `Thread` class, and is request always needed? Maybe there could be a constructor with context and other without?

Parameterless constructors are special and used in many cases, for example `Activator.CreateInstance<T>()` only works for classes with parameterless constructors.

**Comment by jp2masa** [comment] 2018-08-15 00:27
@jakubmisek I'm sorry if I'm boring you, but I think that this should be considered. As I already said, I don't know any implementation details, but parameterless constructors are a special kind of constructors, and this may also introduce confusion for developers, as they will probably expect the constructor to be parameterless, although it's not.

**Comment by jakubmisek** [comment] 2018-08-15 08:11
@jp2masa I agree with you and I'm sure you have a particular case where you'd like to have parameterless ctor. As you said, many PHP features rely on that. And as I stated before, by design, every PHP class requires an instance of `Context`.
Btw the API for creating PHP class is `Context.Create<T>`. Any other way is undocumented and we cannot guarantee its behavior.

**Comment by jakubmisek** [comment] 2019-06-13 17:30
required for https://github.com/peachpiecompiler/peachpie/issues/445

**Comment by jakubmisek** [comment] 2019-06-19 16:51
implemented, closing.

Note, when using parameter-less ctor, created objects are associated/live within current `ExecutionContext`

**Closed by jakubmisek** 2019-06-19 16:51 UTC
Labels: :arrow_double_up:  enhancement, feature
