### ISSUE TITLE
[Bug] VS: Copied file gets added as removed in project file

### ISSUE THREAD

**Issue by robertsundstrom** [peachpiecompiler/peachpie#899] opened 2021-01-29 11:32 UTC
In a PHP project in Visual Studio:

I copy a PHP file in the Solution Explorer, and the copied file gets added as removed to the project file:

```xml
  <ItemGroup>
    <None Remove="themes\bootstrap-starter\checkout.php" />
  </ItemGroup>
```

**Comment by jakubmisek** [comment] 2021-01-29 14:21
thank you for the issue.
As I know we've been fixing this in `1.0.0-preview5` (https://github.com/peachpiecompiler/peachpie/commit/f5285ff02c152f37efa6d92cfc9b8cb9563a132f) 

are you on the latest version?

**Comment by jakubmisek** [comment] 2021-02-05 13:36
confirmed, copy file within solution explorer creates the `<None Remove/>` element in project file

**Comment by jakubmisek** [comment] 2021-02-17 22:15
this seems to be fixed in the `master` branch now, but now sure what changes we made to fix it:

`1.0.0-preview5`:
![drag-copy-file-peachpie-preview5](https://user-images.githubusercontent.com/842150/108274989-eb6f8a00-7175-11eb-879e-188e479c0dd3.gif)

`1.0.0-dev` (latest source code):
![drag-copy-file-peachpie-dev](https://user-images.githubusercontent.com/842150/108275021-f88c7900-7175-11eb-81d3-bc9e618cb899.gif)

**Closed by jakubmisek** 2021-02-17 22:15 UTC
