### ISSUE TITLE
HtmlAgilityPack MissingMethodException

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#447] opened 2019-06-12 13:24 UTC
it seems the compiler generates uncorrect IL code.
```
Exception has occurred: CLR/System.MissingMethodException
An exception of type 'System.MissingMethodException' occurred in HtmlAgilityPackMissingMethodException.dll but was not handled in user code: 'Method not found: 'HtmlAgilityPack.HtmlNode System.Collections.Generic.IEnumerator`1.get_Current()'.'
   at Test.A.fetch(PhpValue content, PhpValue selector) in ~/Desktop/HtmlAgilityPackMissingMethodException/program.php:line 18
   at <Root>.program_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>) in ~/Desktop/HtmlAgilityPackMissingMethodException/program.php:line 35
   at <Script>.Main(String[] args)
```

btw, use an old compiler like `0.9.28`, that is ok!

testcase
[HtmlAgilityPackMissingMethodException.zip](https://github.com/peachpiecompiler/peachpie/files/3281472/HtmlAgilityPackMissingMethodException.zip)

**Comment by jakubmisek** [comment] 2019-06-12 14:27
`MethodMissingException` is not an invalid IL but inconsistent dependencies version.

This is probably caused by a reference to `HtmlAgilityPack` which is also included in PeachPie, using version `1.8.9`

**Comment by liesauer** [comment] 2019-06-13 15:27
i tried using the same version `1.8.9` but it didn't work.
if i take the following code out of function call and exec it directly, everything is fine. so i still think it is a IL problem.
```
    try {
        $document = new \HtmlAgilityPack\HtmlDocument();
        $document->LoadHtml($content);

        $nodes = \Fizzler\Systems\HtmlAgilityPack\HtmlNodeSelection::QuerySelectorAll($document->DocumentNode, $selector);
        if ($nodes) {
            foreach ($nodes as $node) {
                var_dump($node);
            }
        }
    } catch (\Exception $e) { }
```

**Comment by jakubmisek** [comment] 2019-06-27 09:07
thanks @liesauer 
it was really incorrectly generated IL (a generic method `IEnumerator<T>.get_Current` was not "Translated" so it wasn't written up correctly into assembly's metadata :)) )
will be fixed

**Closed** 2019-06-27 09:39 UTC

**Comment by liesauer** [comment] 2019-06-27 09:47
👍
