### ISSUE TITLE
filter_var with FILTER_VALIDATE_URL doesn't work correctly for relative URL paths

### ISSUE THREAD

**Issue by calvinbaart** [peachpiecompiler/peachpie#492] opened 2019-08-21 07:32 UTC
Sample:
```php
echo (filter_var("/test.php", FILTER_VALIDATE_URL) ? "true" : "false") . "\r\n";
echo (filter_var("http://localhost/test.php", FILTER_VALIDATE_URL) ? "true" : "false") . "\r\n";
echo (filter_var("http:///test.php", FILTER_VALIDATE_URL) ? "true" : "false") . "\r\n";
```

PeachPie output:
```
true
true
false
```

PHP output:
```
false
true
false
```

**Comment by jakubmisek** [comment] 2019-08-21 13:11
@calvinbaart  I'm getting 
```
false
true
false
```
as well

**Comment by jakubmisek** [comment] 2019-08-21 18:02
ok that's caused by linux implementation of `System.Uri`

**Comment by jakubmisek** [comment] 2019-08-21 18:21
fixed, closing

**Closed by jakubmisek** 2019-08-21 18:21 UTC
