### ISSUE TITLE
BUILDTASK : error PHP4002 when building php library

### ISSUE THREAD

**Issue by jadiaz** [peachpiecompiler/peachpie#907] opened 2021-02-15 20:32 UTC
There doesn't seem to be any additional information regarding the error.

**Comment by jakubmisek** [comment] 2021-02-15 20:45
Thanks for the issue; the missing error message has been added.

The error text is - "a file is a binary file instead of a text" - which means some source file cannot be decoded as a text. This is usually caused by culture-specific characters in the source file.

The problem is, since there was no additional information, you can't see what file is causing it ..

**Comment by jadiaz** [comment] 2021-02-15 21:12
@jakubmisek thanks for the quick reply. Is there a way past this to see if the project will work?

**Comment by jakubmisek** [comment] 2021-02-15 21:32
You can force specific "CodePage" to be used, so the source files will be read properly.

If running on a command line, specify the CodePage property:
```
dotnet build /p:CodePage=us-ascii
```
Or edit the project file (e.g. if running from Visual Studio), and add the following:
```xml
<PropertyGroup>
  <CodePage>us-ascii</CodePage>
</PropertyGroup>
```

You can try changing `us-ascii` for `windows-1252`, or your specific local code page.

Once updated PeachPie will be released, the `PHP4002` error will say the affected file.

**Comment by jadiaz** [comment] 2021-02-15 21:49
Thanks, that helped! I now have a lot of warning messages

**Comment by jakubmisek** [comment] 2021-02-15 21:51
good!

Is the project based on an opensource framework?

**Comment by jadiaz** [comment] 2021-02-15 22:05
unfortunately no it is not.

**Comment by jakubmisek** [comment] 2021-02-17 21:59
Closing the issue, please let us know if there would be any other "unexpected" warnings or errors.

**Closed by jakubmisek** 2021-02-17 21:59 UTC
