### ISSUE TITLE
Pchp.Core.PhpString.Blob.Pchp.Core.IPhpArray.EnsureItemArray(IntStringKey key)  Specified method is not supported.

### ISSUE THREAD

**Issue by xbIm** [peachpiecompiler/peachpie#353] opened 2019-01-27 12:11 UTC
I'm getting "Specified method is not supported." not implemented on posting update to Wordpress post

will this method be implemented?
https://github.com/peachpiecompiler/peachpie/blob/c8b13abba1fbfab87cf93c97088b5c3d7b797ac1/src/Peachpie.Runtime/PhpString.cs#L1338

Is there any workaround?

StackTraces:
```fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLK49MJOPQ36", Request id "0HLK49MJOPQ36:00000027": An unhandled exception was thrown by the application.
System.NotSupportedException: Specified method is not supported.
   at Pchp.Core.PhpString.Blob.Pchp.Core.IPhpArray.EnsureItemArray(IntStringKey key)
   at Pchp.Core.Utilities.NameValueCollectionUtils.EnsureItemArray(IPhpArray array, IntStringKey key)
   at Pchp.Core.Utilities.NameValueCollectionUtils.AddVariable(IPhpArray array, String name, String value, String subname)
   at Peachpie.AspNetCore.Web.RequestContextCore.AddVariables(PhpArray target, IEnumerable`1 values)
   at Peachpie.AspNetCore.Web.RequestContextCore.InitPostVariable()
   at Pchp.Core.Context.InitSuperglobals(Superglobals& superglobals)
   at Peachpie.AspNetCore.Web.RequestContextCore..ctor(HttpContext httpcontext, String rootPath, Encoding encoding)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at PeachPied.WordPress.AspNetCore.Internal.DiagnosticExtensions.Middleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jakubmisek** [comment] 2019-01-28 10:32
thanks @xbIm !
the issue is following URL
`http://localhost:5004/?a=hello&a[]=world`

internally we create `$_GET["a"] = "hello" : string`
and then attempt to treat it as array `$_GET["a"][] = "world"` which fails because $_GET["a"] is a string already (not array). 

Will be fixed as it is in PHP, so "hello" will be dropped! (personally I think this is fault in the code that generates such URL and it should be reported, but we have to keep compatibility with PHP so ...)

**Closed** 2019-01-28 10:49 UTC
